package com.itesco.mayzapp;

public class ARECOMENDACIONES {
    /*

        TODO ESTA LISTO!

        SE REQUIERE DE LOS METODOS PARA  INICIO DE SESION, DETECCION DE CONTRASEÑAS, BASE DE DATOS, ETC.

        EXITE UNA PANTALLA DE ERROR... SE LLAMA ERROR.CLASS

        SI TIENE ALGUNA DUDA MANDEME UN MENSAJE/CORREO/INBOX

        LE DEJE UN LINK QUE PUEDE SER DE UTILIDAD A LA HORA DE HACER EL TEXT VIEW A PDF ESPERO LE SIRVA SI ES QUE NO TIENE OTRO CODIGO

        Alberto Alexis Dominguez Ruiz
        Ing, Informática
        ITESCO 2019(C)
    

    */
}
